# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build
on: push

jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14]
    steps:
      - name: my first step
        env:
          MY_VAR: Salut
          FIRST_NAME: Bruno
          LAST_NAME: Gachie
        run: echo $MY_VAR $FIRST_NAME $LAST_NAME
