name: test
on:
  pull_request:
    branches: master
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    stratedy:
      matrix:
        node: [12]
        os: [macos-latest, windows-latest, ubunto-18.04]
        include:
          - node: 13
            os: ubuntu-18.04
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.os }}
        uses: actions/setup-nodes@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
    
